saleor/api/product/urls.py
from django.conf.urls import url

from .views import (
    CreateStockAPIView,    
    ProductListAPIView,
    ProductStockListAPIView,
    SearchSkuListAPIView,
    SalesListAPIView,
    SalesCreateAPIView,
    SalesDetailAPIView,
    SalesDeleteAPIView,
    CreditorsListAPIView,
    )


urlpatterns = [
    url(r'^$', ProductListAPIView.as_view(), name='product-list'),
    url(r'^stock$', ProductStockListAPIView.as_view(), name='productstock-list'),
    url(r'^stock/(?P<stock_pk>[0-9]+)$', CreateStockAPIView.as_view(), name='create-stock'),
    url(r'^search-sku/$', SearchSkuListAPIView.as_view(), name='search-sku'),
    url(r'^list-orders/$', SalesListAPIView.as_view(), name='list-orders'),
    url(r'^pending-payment/$', CreditorsListAPIView.as_view(), name='payment-pending'),
    url(r'^create-order/$', SalesCreateAPIView.as_view(), name='create-order'),    
    url(r'^sales-details/(?P<pk>[0-9]+)/$', SalesDetailAPIView.as_view(), name='sales-details'),
    url(r'^sales-delete/(?P<pk>[0-9]+)/$', SalesDeleteAPIView.as_view(), name='sales-delete'),

]

saleor/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category'),
    url(r'(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/add/$',
        views.product_add_to_cart, name="add-to-cart"),
]

saleor/search/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.search, name='search')
]

saleor/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .accounts.urls import urlpatterns as accounts_urls
from .api.allocate.urls import urlpatterns as api_allocate_urls
from .api.attribute.urls import urlpatterns as api_attribute_urls
from .api.car.urls import urlpatterns as api_car_urls
from .api.cash.urls import urlpatterns as api_cash_urls
from .api.category.urls import urlpatterns as api_category_urls
from .api.customer.urls import urlpatterns as api_customer_urls
from .api.discount.urls import urlpatterns as api_discount_urls
from .api.invoice.urls import urlpatterns as api_invoice_urls
from .api.credit.urls import urlpatterns as api_credit_urls
from .api.order_number.urls import urlpatterns as api_order_number_urls
from .api.payment.urls import urlpatterns as api_payment_urls
from .api.sale.urls import urlpatterns as api_sale_urls
from .api.product.urls import urlpatterns as api_urls
from .api.settings.urls import urlpatterns as api_settings_urls
from .api.sms.urls import urlpatterns as api_sms_urls
from .api.terminal.urls import urlpatterns as api_terminal_urls
from .api.user.urls import urlpatterns as api_user_urls
from .api.variant.urls import urlpatterns as api_variant_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .payment.urls import urlpatterns as payment_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls
import notifications.urls
from .api.product import views as api_views
from .api.login import ObtainJSONWebToken
from . import decorators


urlpatterns = [    
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),
    url(r'^api/allocate/', include(api_allocate_urls, namespace='allocate-api')),
    url(r'^api/attribute/', include(api_attribute_urls, namespace='attribute-api')),
    url(r'^api/car/', include(api_car_urls, namespace='car-api')),
    url(r'^api/category/', include(api_category_urls, namespace='category-api')),
    url(r'^api/cash/', include(api_cash_urls, namespace='cash-api')),
    url(r'^api/credit/', include(api_credit_urls, namespace='credit-api')),
    url(r'^api/customer/', include(api_customer_urls, namespace='customer-api')),
    url(r'^api/discount/', include(api_discount_urls, namespace='discount-api')),
    url(r'^api/invoice/', include(api_invoice_urls, namespace='invoice-api')),
    url(r'^api/order_number/', include(api_order_number_urls, namespace='order_number-api')),
    url(r'^api/products/', include(api_urls, namespace='product-api')),
    url(r'^api/payment/', include(api_payment_urls, namespace='payment-api')),
    url(r'^api/sale/', include(api_sale_urls, namespace='sale-api')),
    url(r'^api/settings/', include(api_settings_urls, namespace='settings-api')),
    url(r'^api/sms/', include(api_sms_urls, namespace='terminal-api')),
    url(r'^api/terminal/', include(api_terminal_urls, namespace='terminal-api')),
    url(r'^api/user/', include(api_user_urls, namespace='user-api')),
    url(r'^api/variant/', include(api_variant_urls, namespace='variant-api')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^payment/', include(payment_urls, namespace='payment')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
    #jwt post token code url
    # url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/auth/token/', ObtainJSONWebToken.as_view()),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/product/models.py
from __future__ import unicode_literals

import datetime
from decimal import Decimal

from django.conf import settings
from django.contrib.postgres.fields import HStoreField
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator, RegexValidator
from django.db import models
from django.utils.timezone import now
from django.db.models import F, Max, Q, Sum
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django.utils.text import slugify
from django.utils.translation import pgettext_lazy
from django.utils import six
from django_prices.models import PriceField
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from prices import PriceRange
from satchless.item import InsufficientStock, Item, ItemRange
from text_unidecode import unidecode
from versatileimagefield.fields import VersatileImageField, PPOIField

from ..discount.models import calculate_discounted_price
from ..supplier.models import Supplier
from ..search import index
from saleor.payment.models import PaymentOption
from .utils import get_attributes_display_map
from . import Status


@python_2_unicode_compatible
class Category(MPTTModel):
    name = models.CharField(
        pgettext_lazy('Category field', 'name'), max_length=128,unique=True)
    slug = models.SlugField(
        pgettext_lazy('Category field', 'slug'), max_length=50)
    description = models.TextField(
        pgettext_lazy('Category field', 'description'), blank=True)
    parent = models.ForeignKey(
        'self', null=True, blank=True, related_name='children',
        verbose_name=pgettext_lazy('Category field', 'parent'))
    hidden = models.BooleanField(
        pgettext_lazy('Category field', 'hidden'), default=False)

    objects = models.Manager()
    tree = TreeManager()

    class Meta:
        verbose_name = pgettext_lazy('Category model', 'category')
        verbose_name_plural = pgettext_lazy('Category model', 'categories')
        app_label = 'product'

    def __str__(self):
        return self.name

    def get_product_num(self):
        return len(self.products.all())
    def get_absolute_url(self, ancestors=None):
        return reverse('product:category',
                       kwargs={'path': self.get_full_path(ancestors),
                               'category_id': self.id})

    def get_full_path(self, ancestors=None):
        if not self.parent_id:
            return self.slug
        if not ancestors:
            ancestors = self.get_ancestors()
        nodes = [node for node in ancestors] + [self]
        return '/'.join([node.slug for node in nodes])

    def set_hidden_descendants(self, hidden):
        self.get_descendants().update(hidden=hidden)


@python_2_unicode_compatible
class ProductClass(models.Model):
    name = models.CharField(
        pgettext_lazy('Product class field', 'name'), max_length=128, unique=True)
    has_variants = models.BooleanField(
        pgettext_lazy('Product class field', 'has variants'), default=True)
    product_attributes = models.ManyToManyField(
        'ProductAttribute', related_name='products_class', blank=True,
        verbose_name=pgettext_lazy('Product class field',
                                   'product attributes'))
    variant_attributes = models.ManyToManyField(
        'ProductAttribute', related_name='product_variants_class', blank=True,
        verbose_name=pgettext_lazy('Product class field', 'variant attributes'))
    is_shipping_required = models.BooleanField(
        pgettext_lazy('Product class field', 'is shipping required'),
        default=False)

    class Meta:
        verbose_name = pgettext_lazy(
            'Product class model', 'product class')
        verbose_name_plural = pgettext_lazy(
            'Product class model', 'product classes')
        app_label = 'product'

    def __str__(self):
        return self.name

    def __repr__(self):
        class_ = type(self)
        return '<%s.%s(pk=%r, name=%r)>' % (
            class_.__module__, class_.__name__, self.pk, self.name)


class ProductTax(models.Model):    
    tax_name = models.CharField(
        pgettext_lazy('Tax name', 'Tax name (optional)'),
        max_length=128, blank=True)   
    tax_label = models.CharField(
        pgettext_lazy('Label on invoices', 'Short text printed on invoices'),
        max_length=128, blank=True)
    tax = models.IntegerField(pgettext_lazy('Product Tax', 'tax %'),
        validators=[MinValueValidator(0)], unique=True, default=Decimal(0))

    def __str__(self):
        return self.tax_name + ' ' + str(self.tax)+' %'

    def get_tax(self):
        return self.tax


class ProductManager(models.Manager):

    def get_available_products(self):
        today = datetime.date.today()
        return self.get_queryset().filter(
            Q(available_on__lte=today) | Q(available_on__isnull=True))


@python_2_unicode_compatible
class Product(models.Model, ItemRange, index.Indexed):
    product_class = models.ForeignKey(
        ProductClass, related_name='products',
        verbose_name=pgettext_lazy('Product field', 'product class'))
    product_tax = models.ForeignKey(
        ProductTax, related_name='producttax',blank=True, null=True,
        verbose_name=pgettext_lazy('Product field', 'product class'))
    name = models.CharField(
        pgettext_lazy('Product field', 'name'),unique=True, max_length=128)
    description = models.TextField(
        verbose_name=pgettext_lazy('Product field', 'description'), blank=True, null=True)
    categories = models.ManyToManyField(
        Category, verbose_name=pgettext_lazy('Product field', 'categories'),
        related_name='products')
    price = PriceField(
        pgettext_lazy('Product field', 'price'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12,
        validators=[MinValueValidator(0)], default=Decimal(0), decimal_places=2)
    minimum_price = PriceField(
        pgettext_lazy('Product variant field', 'minimum price'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        blank=True, null=True)
    wholesale_price = PriceField(
        pgettext_lazy('Product field', 'Wholesale price'),
        currency=settings.DEFAULT_CURRENCY, blank=True,null=True, max_digits=12, decimal_places=2)
    product_supplier = models.ForeignKey(
        Supplier, related_name='suppliers', blank=True, null=True,
        verbose_name=pgettext_lazy('Product field', 'product supplier'))
    
    available_on = models.DateField(
        pgettext_lazy('Product field', 'available on'), blank=True, null=True)
    attributes = HStoreField(pgettext_lazy('Product field', 'attributes'),
                             default={})
    updated_at = models.DateTimeField(
        pgettext_lazy('Product field', 'updated at'), auto_now=True, null=True)
    is_featured = models.BooleanField(
        pgettext_lazy('Product field', 'is featured'), default=False)
    low_stock_threshold = models.IntegerField(
        pgettext_lazy('Product field', 'low stock threshold'),
        validators=[MinValueValidator(0)], null=True,blank=True, default=Decimal(10))
    

    objects = ProductManager()

    search_fields = [
        index.SearchField('name', partial_match=True),
        index.SearchField('description'),
        index.FilterField('available_on')]

    class Meta:
        app_label = 'product'
        verbose_name = pgettext_lazy('Product model', 'product')
        verbose_name_plural = pgettext_lazy('Product model', 'products')

    def __iter__(self):
        if not hasattr(self, '__variants'):
            setattr(self, '__variants', self.variants.all())
        return iter(getattr(self, '__variants'))

    def __repr__(self):
        class_ = type(self)
        return '<%s.%s(pk=%r, name=%r)>' % (
            class_.__module__, class_.__name__, self.pk, self.name)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:details', kwargs={'slug': self.get_slug(),
                                                  'product_id': self.id})

    def get_slug(self):
        return slugify(smart_text(unidecode(self.name)))
    
    def get_product_tax(self):
        return self.product_tax

    def get_tax_value(self):
        return self.product_tax.get_tax()

    def is_in_stock(self):
        return any(variant.is_in_stock() for variant in self)

    def total_stock(self):
        return Sum(self.variant.stock.stock_available())

    def total_variants(self):
        return len(self.variants.all())

    def get_first_category(self):
        for category in self.categories.all().order_by('id'):
            if not category.hidden:
                return category
        return None

    def get_variants_count(self):
        variants = self.variants.filter(product=self.pk)
        total = 0
        for stock in variants:
            total += stock.get_stock_quantity()
        return total

    def is_available(self):
        today = datetime.date.today()
        return self.available_on is None or self.available_on <= today

    def get_first_image(self):
        first_image = self.images.first()

        if first_image:
            return first_image.image
        return None

    def get_attribute(self, pk):
        return self.attributes.get(smart_text(pk))

    def set_attribute(self, pk, value_pk):
        self.attributes[smart_text(pk)] = smart_text(value_pk)

    def get_price_range(self, discounts=None,  **kwargs):
        if not self.variants.exists():
            price = calculate_discounted_price(self, self.price, discounts,
                                               **kwargs)
            return PriceRange(price, price)
        else:
            return super(Product, self).get_price_range(
                discounts=discounts, **kwargs)


class ProductVariantManager(models.Manager):

    def get_low_stock(self):
        today = datetime.date.today()

saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor/search/forms.py
from django import forms
from django.utils.translation import pgettext

from .backends import get_search_backend


class SearchForm(forms.Form):
    q = forms.CharField(label=pgettext('Search form label', 'Query'), required=True)

    def search(self, model_or_queryset):
        backend = get_search_backend('default')
        query = self.cleaned_data['q']
        results = backend.search(query, model_or_queryset=model_or_queryset)
        return results

templates/dashboard/product/subcategory/products/view.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load product_first_image from product_images %}
{% load i18n %}
{% load prices_i18n %}
{% load humanize %}

{% block title %}
  Products List
{% endblock %}

 {% block breadcrumbs %}
    <li><a href="{% url 'dashboard:product-class-list' %}">Sub Categories</a></li>
    <li class="active"><a href="{% url 'dashboard:subcategory-products' pk=product_pk %}">{{subcategory_name|title}}</a></li>
 {% endblock %}

{% block menu_product_classes_class %}active{% endblock %}
 {% block custom_css %}
   <style type="text/css">
     .clickable-row td.td{
      cursor: pointer;
     }
     tr.nb td{border:0px;}
     .nb{border:0px;}
     .table{border:1px solid #ccc}
     .edit-dropdown{
         min-width:150px;
         padding-top:0px;
         padding-bottom:0px;
     }
   </style>
 {% endblock %}

{% block content %}
 <div class="row animated fadeIn">
   <div class="col-md-12">
      <div class="panel panel-flat">
      
        <div class="panel-body search-panel">
        <div class="col-md-2">
              <label style="visibility: hidden;"> add</label>
              <div class="form-group">
                {% if perms.product.add_product %}
                 <a class="btn btn-primary text-white btn-xs  hvr-glow btn-raised legitRipple waves-effect waves-light teal modal-trigger" href="{% url 'dashboard:product-add' %}" title="{% trans "Add product" context "Product list add button text" %}">
                  <i class="icon-plus3 position-left"></i>Add Product
                </a>
                {% endif %}
              </div>
            </div>
            <div class="col-md-4">
             <label>Search Products</label>
              <div class="form-group form-group-material has-feedback">
                <input class="form-control search_user" placeholder="Search Products" type="text">
                <div class="form-control-feedback">
                  <i class="icon-search4 text-size-base"></i>
                </div>
              </div>
            </div>
            <div class="col-md-2 hidden">
              <label>display list size</label>
              <div class="form-group">
                 <select class="bootstrap-select list-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="0" selected>No:</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                  </select>
              </div>
            </div>
            <div class="col-md-2 hidden">
             <label>Export</label>
              <div class="form-group">
                 <select class="bootstrap-select export-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="none" data-icon="fa fa-dot-circle-o">Option</option>
                    <option value="pdf" data-icon="fa-file-pdf-o">export pdf</option>
                    <option value="excel" data-icon="fa-file-excel-o">export excel</option>
                  </select>
              </div>
            </div>
            
        </div>
      </div>
   </div>
  {% if product_results %}
  <div class="col-md-12">
   <div id="pagination-div">
      <!-- Header and footer fixed -->
      <div class="panel panel-flat">
        <div class="panel-body">
        <div class="table-responsives">
            <table class="table table-striped table-hover fixed_headers datatable-header-footer" style="border-bottom:1px solid #ddd;">
                <thead>
                  <tr class="bg-primary">
                     <th></th>
                      <th>Image</th>
                      <th>Product Name</th>
                      <th>Category</th>
                      <th>Price (KShs)</th>
                      <th>Current Stock</th>
                      <th class="text-center">Options</th>
                  </tr>
                </thead>
                <tbody id="tb">
                {% for product in product_results %}
                    <tr data-title=" {{ product.name }} " class="clickable-row">
                      <td href="#modal_instance_lg" class="modal-trigger-ajax" data-title="Product Details" data-href="{% url 'dashboard:product-update' pk=product.pk %}"></td>
                      <!-- image -->
                      <td href="#modal_instance_lg" class="modal-trigger-ajax" data-title="Product Details" data-href="{% url 'dashboard:product-update' pk=product.pk %}"><img src="{% product_first_image product size="60x60" method="crop" %}"
                       srcset="{% product_first_image product size="60x60" method="crop" %} 1x, {% product_first_image product size="120x120" method="crop" %} 2x"
                       alt="" class="circle teal"></td>
                       <!-- product name -->
                      <td href="#modal_instance_lg" class="modal-trigger-ajax" data-title="Product Details"data-href="{% url 'dashboard:product-update' pk=product.pk %}">{{ product.name }}</td>
                      <!-- product category -->
                      <td href="#modal_instance_lg" class="modal-trigger-ajax" data-title="Product Details" data-href="{% url 'dashboard:product-update' pk=product.pk %}">
                        {% with product.get_first_category as category %}
                        {% if category %}
                        {{ category }}
                        {% endif %}
                        {% endwith %}
                      </td>
                      <!-- price -->
                        <td href="#modal_instance_lg" class="modal-trigger-ajax" data-title="Product Details" data-href="{% url 'dashboard:product-update' pk=product.pk %}"> <span class="pull-right">{% gross product.price html=True %}</span></td>
                      <!-- variants -->
                      <td href="#modal_instance_lg" class="modal-trigger-ajax" data-title="Product Details" data-href="{% url 'dashboard:product-update' pk=product.pk %}">

                      {{ product.get_variants_count }}

                      </td>
                  <!-- actions -->
                      <td class="action-data">
                          <!-- Single button -->
                        <div class="btn-group">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            action <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu edit-dropdown">
                            <li>
                                <a href="{% url 'dashboard:product-update' pk=product.pk %}">
                                    <i class="icon-pencil7" data-popup="tooltip" title='Edit product' data-placement="bottom" data-original-title="Edit me">
                                    </i> EDIT
                                </a>
                            </li>
                            <li>
                                <a href="#modal_instance" data-title='Remove {{ product.name }}' data-href="{% url 'dashboard:product-delete' pk=product.pk %}"
                            class="modal-trigger-ajax">
                                    <i class="icon-trash position-left" data-popup="tooltip" title='Edit product' data-placement="bottom" data-original-title="Delete me">
                                    </i> DELETE
                                </a>
                            </li>
                          </ul>
                        </div>

                      </td>
                    </tr>
                      {% endfor %}
                </tbody>
           </table>

        </div>
        </div>
         <div class="my-paginate">
             <div class="row">
         <div class="col-md-12">
          <div class="col-md-4">
           <div class="col-md-12">
            <div class="col-md-6 mt-10">
             <label>display list size</label>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                 <select class="bootstrap-select list-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="0" selected>No:</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                  </select>
              </div>
            </div>
          </div>
          </div>
          <div class="col-md-4">
           <div class="text-center bootpag-callback" style="">
             <div class="my-paginate">
             <ul class="pagination bootpag pagination-flat pagination-sm" style="margin-bottom: 0px;"></ul>
             </div>
            </div>
           </div>
            <div class="col-md-4">
             <div class="col-md-12">
              <div class="pull-right pages-nav">Page 1 of {{totalp}}</div>
             </div>
            </div>
          </div>
         </div>
         <input type="hidden" id="page_size" val="">

         </div>
      </div>
    </div><!-- pagination -->
  </div>
     {% else %}
  <div class="col-md-12 animated fadeIn ">
   <div class="panel bg-danger-600">
     <div class="panel-body">
       <div style="text-align: center;font-size:16px;">
        No Products available
       </div>
      </div>
    </div>
  </div>
{% endif %}
</div>

{% include "dashboard/includes/_modal_template.html"  %}
{% include "dashboard/includes/_modal_large.html"  %}
{% endblock%}
{% block custom_js %}
  <script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script>
  <script type="text/javascript" src="{% static 'backend/js/pages/form_multiselect.js' %}"></script>
<script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_select.min.js' %}"></script>



<script type="text/javascript">
$(document).ready(function() {

  //** view product modal
  $( "body").on('click', '.modal-trigger-ajax', function() {

    var url = $(this).data('href')
    var prompt_text = $(this).data('title');
    var modal = $(this).attr('href');
    var csrf_token = $(this).data('csrf_token')
    $('.modal-title').html(prompt_text);
    $(".results" ).empty().append('<span class="text-center" style="padding:23px">Loading...<i class=" icon-spinner"></i></span>');
    $(modal).modal();
      var posting = $.get( url, {'csrfmiddlewaretoken':csrf_token });
      // Put the results in a div
      posting.done(function( data ) {
      $(".results" ).empty().append( data );

      });

   });


    $('.export-sz').selectpicker({
          iconBase: 'fa',
          tickIcon: 'fa-dot-circle-o',
          pdfIcon:'fa-file-pdf-o',
          excelIcon:'fa-file-excel-o'
    }).on('change', function(){

        var ts = $(this).val();
        if(ts == 'pdf'){
          var url = "{% url 'dashboard:users_pdf' %}";
          window.open(url, '_blank');

        }else if(ts=='excel'){
          window.location="{% url 'dashboard:users_export_csv' %}";

        }else{
          $(this).val('')
        }
    });

    //**@ display size select
    $('.list-sz').selectpicker().on('change', function(){
        var ts = $(this).val();
        if(ts != '0'){
            $.ajax({ url: "{% url 'dashboard:subcategory-products-paginate' %}",type: 'GET',data: {page:1, size:ts, product_pk:'{{product_pk}}' },
            async:false,success: function(data){
                  $('#pagination-div').html(data);
            }});
        }

     });

    $('.bootpag-callback').bootpag({
         total: parseInt({{totalp}}),
         maxVisible: 3,
         leaps: true,
         firstLastUse: true,
         first: 'First',
         last: 'Last',       
         wrapClass: 'pagination',
         activeClass: 'active',
         disabledClass: 'disabled',
         nextClass: 'next',
         prevClass: 'prev',
         lastClass: 'last',
         firstClass: 'first',      

        
        }).on("page", function(event, num){
            $(".pages-nav").html("Page " + num +" of "+{{totalp}}); // or some ajax content loading...
            $.get("{% url 'dashboard:subcategory-products-paginate' %}",{page:num, product_pk:'{{product_pk}}' },
            function(data){
               $('#tb').html(data);
            });
    }).children('.pagination').addClass('pagination-flat pagination-sm')

      var delay = (function(){
        var timer = 0;
        return function(callback, ms){
          clearTimeout (timer);
          timer = setTimeout(callback, ms);
        };
      })();

      $('.search_user').keyup(function() {
        var search_text = $(this).val();
        delay(function(){
           var url = "{% url 'dashboard:subcategory-products-search' %}";
           $.ajax({ url:url, type: 'GET',data: {page:1, q:search_text, product_pk:'{{product_pk}}' },
           success: function(data){
                  $('#pagination-div').html(data);
           }});
        }, 500 );

      });

  });




</script>
{% endblock %}