saleor/api/credit/urls.py
from django.conf.urls import url

from .views import (    
    CreditCreateAPIView,
    CreditListAPIView,
    CreditorsListAPIView,
    CreditUpdateAPIView,    
    )


urlpatterns = [
    url(r'^$', CreditListAPIView.as_view(), name='list-credit'),
    url(r'^search-credit/$', CreditorsListAPIView.as_view(), name='search-credit'),
    url(r'^update-credit/(?P<pk>[0-9]+)/$', CreditUpdateAPIView.as_view(), name='update-credit'),
    url(r'^create-credit/$', CreditCreateAPIView.as_view(), name='create-credit'),
    
]

saleor/dashboard/credit/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views,charts, pdfs,  purchase, sales_margin, sales_tax, sales_margin2
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
        url(r'^$', permission_required('reports.view_sale_reports', login_url='not_found')
            (views.credit_list), name='credit_list'),
        url(r'^history/(?P<credit_pk>[0-9]+)/$', permission_required('reports.view_sale_reports', login_url='not_found')
            (views.credit_history), name='credit_history'),
        url(r'^history/pdf/(?P<pk>[0-9]+)/$', permission_required('reports.view_sale_reports', login_url='not_found')
            (views.credit_detail_pdf), name='credit_history_pdf'),
        url(r'^credit/$', permission_required('reports.view_sale_reports', login_url='not_found')
            (views.credit_reports), name='credit_reports'),
        url(r'^detail/(?P<pk>[0-9]+)/$', permission_required('reports.view_sale_reports', login_url='not_found')
            (views.credit_detail), name='credit-detail'),

        url( r'^credit_search/$', views.credit_search, name = 'credit_search' ),
        url( r'^credit_paginate/$', views.credit_paginate, name = 'credit_paginate'),


        url(r'^reports/credit/list/pdf/$', pdfs.sales_list_pdf, name='reports_credit_list_pdf'),

        url(r'^reports/credit/category/pdf/$', pdfs.sales_category, name='reports_credit_category_pdf'),
        url(r'^reports/credit/items/pdf/$', pdfs.sales_items, name='reports_credit_items_pdf'),
        url(r'^reports/credit/user/pdf/$', pdfs.sales_user, name='reports_credit_user_pdf'),
        url(r'^reports/credit/till/pdf/$', pdfs.sales_tills, name='reports_credit_tills_pdf'),
        url(r'^pdf/credit/detail/(?P<pk>[0-9]+)/$', permission_required('reports.view_credit_reports', login_url='not_found')
            (pdfs.sales_detail), name='pdf-credit-detail'),
        url(r'^reports/sales/list/export_csv/$', views.sales_list_export_csv, name='reports_credit_list_export_csv'),


        url( r'^sales/margin/$', sales_margin.sales_margin, name = 'credit_margin' ),
        url( r'^sales/tax/report/$', sales_margin.sales_tax, name = 'credit_tax' ),
        url( r'^credit/sale/notifier/$', views.due_credit_notifier, name = 'due_credit_notifier' ),

]

if settings.DEBUG:	
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/search/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.search, name='search')
]

saleor/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .accounts.urls import urlpatterns as accounts_urls
from .api.allocate.urls import urlpatterns as api_allocate_urls
from .api.attribute.urls import urlpatterns as api_attribute_urls
from .api.car.urls import urlpatterns as api_car_urls
from .api.cash.urls import urlpatterns as api_cash_urls
from .api.category.urls import urlpatterns as api_category_urls
from .api.customer.urls import urlpatterns as api_customer_urls
from .api.discount.urls import urlpatterns as api_discount_urls
from .api.invoice.urls import urlpatterns as api_invoice_urls
from .api.credit.urls import urlpatterns as api_credit_urls
from .api.order_number.urls import urlpatterns as api_order_number_urls
from .api.payment.urls import urlpatterns as api_payment_urls
from .api.sale.urls import urlpatterns as api_sale_urls
from .api.product.urls import urlpatterns as api_urls
from .api.settings.urls import urlpatterns as api_settings_urls
from .api.sms.urls import urlpatterns as api_sms_urls
from .api.terminal.urls import urlpatterns as api_terminal_urls
from .api.user.urls import urlpatterns as api_user_urls
from .api.variant.urls import urlpatterns as api_variant_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .payment.urls import urlpatterns as payment_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls
import notifications.urls
from .api.product import views as api_views
from .api.login import ObtainJSONWebToken
from . import decorators


urlpatterns = [    
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),
    url(r'^api/allocate/', include(api_allocate_urls, namespace='allocate-api')),
    url(r'^api/attribute/', include(api_attribute_urls, namespace='attribute-api')),
    url(r'^api/car/', include(api_car_urls, namespace='car-api')),
    url(r'^api/category/', include(api_category_urls, namespace='category-api')),
    url(r'^api/cash/', include(api_cash_urls, namespace='cash-api')),
    url(r'^api/credit/', include(api_credit_urls, namespace='credit-api')),
    url(r'^api/customer/', include(api_customer_urls, namespace='customer-api')),
    url(r'^api/discount/', include(api_discount_urls, namespace='discount-api')),
    url(r'^api/invoice/', include(api_invoice_urls, namespace='invoice-api')),
    url(r'^api/order_number/', include(api_order_number_urls, namespace='order_number-api')),
    url(r'^api/products/', include(api_urls, namespace='product-api')),
    url(r'^api/payment/', include(api_payment_urls, namespace='payment-api')),
    url(r'^api/sale/', include(api_sale_urls, namespace='sale-api')),
    url(r'^api/settings/', include(api_settings_urls, namespace='settings-api')),
    url(r'^api/sms/', include(api_sms_urls, namespace='terminal-api')),
    url(r'^api/terminal/', include(api_terminal_urls, namespace='terminal-api')),
    url(r'^api/user/', include(api_user_urls, namespace='user-api')),
    url(r'^api/variant/', include(api_variant_urls, namespace='variant-api')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^payment/', include(payment_urls, namespace='payment')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
    #jwt post token code url
    # url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/auth/token/', ObtainJSONWebToken.as_view()),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor/search/forms.py
from django import forms
from django.utils.translation import pgettext

from .backends import get_search_backend


class SearchForm(forms.Form):
    q = forms.CharField(label=pgettext('Search form label', 'Query'), required=True)

    def search(self, model_or_queryset):
        backend = get_search_backend('default')
        query = self.cleaned_data['q']
        results = backend.search(query, model_or_queryset=model_or_queryset)
        return results

saleor/api/credit/views.py
from django.db.models import Q
from django.contrib.auth import get_user_model
from rest_framework import generics

from ...decorators import user_trail
from ...credit.models import Credit
from ...sale.models import (
                            Sales, SoldItem,
                            Terminal, 
                            TerminalHistoryEntry,
                            DrawerCash
                            )
from .serializers import (
    CreditListSerializer,
    CreateCreditSerializer,
    CreditUpdateSerializer,    
     )

import logging
User = get_user_model()
debug_logger = logging.getLogger('debug_logger')
info_logger = logging.getLogger('info_logger')
error_logger = logging.getLogger('error_logger')


class CreditDetailAPIView(generics.RetrieveAPIView):
    queryset = Credit.objects.all()
    serializer_class = CreditListSerializer


class CreditCreateAPIView(generics.CreateAPIView):
    queryset = Credit.objects.all()
    serializer_class = CreateCreditSerializer

    def perform_create(self, serializer):              
        instance = serializer.save(user=self.request.user)      
        if instance.status == 'fully-paid':
            send_to_sale(instance)


class CreditListAPIView(generics.ListAPIView):
    serializer_class = CreditListSerializer

    def get_queryset(self, *args, **kwargs):        
        queryset_list = Credit.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(
                Q(invoice_number__icontains=query)               
                ).distinct()
        return queryset_list


class CreditorsListAPIView(generics.ListAPIView):    
    serializer_class = CreditListSerializer

    def get_queryset(self, *args, **kwargs):        
        queryset_list = Credit.objects.filter(status='payment-pending')
        query = self.request.GET.get('q')
        try:
            if query:
                queryset_list = queryset_list.filter(status='payment-pending').filter(
                    Q(invoice_number__icontains=query)|
                    Q(customer__name__icontains=query)|
                    Q(created__icontains=query) |
                    Q(customer__mobile__icontains=query)).distinct()
        except:
            print('nothing found')
        return queryset_list


class CreditUpdateAPIView(generics.RetrieveUpdateAPIView):    
    queryset = Credit.objects.all()
    serializer_class = CreditUpdateSerializer

    def perform_update(self, serializer):
        instance = serializer.save(user=self.request.user)
        if instance.status == 'fully-paid':
            send_to_sale(instance)
        user_trail(self.request.user.name,'made a credit sale:#'+str(serializer.data['invoice_number'])+' credit sale worth: '+str(serializer.data['total_net']),'add')
        info_logger.info('User: '+str(self.request.user)+' made a credit sale:'+str(serializer.data['invoice_number']))
        terminal = Terminal.objects.get(pk=int(serializer.data['terminal']))
        trail = 'User: '+str(self.request.user)+\
                ' updated a credited sale :'+str(serializer.data['invoice_number'])+\
                ' Net#: '+str(serializer.data['total_net'])+\
                ' Amount paid#:'+str(serializer.data['amount_paid'])

        TerminalHistoryEntry.objects.create(
                            terminal=terminal,
                            comment=trail,
                            crud='deposit',
                            user=self.request.user
                        )
        drawer = DrawerCash.objects.create(manager=self.request.user,                                        
                                           user=self.request.user,
                                           terminal=terminal,
                                           amount=serializer.data['amount_paid'],
                                           trans_type='credit paid')
        

def send_to_sale(credit):
    sale = Sales.objects.create(
                         user=credit.user,
                         invoice_number=credit.invoice_number,
                         total_net=credit.total_net,
                         sub_total=credit.sub_total,
                         balance=credit.balance,
                         terminal=credit.terminal,
                         amount_paid=credit.amount_paid,
                         customer=credit.customer,
                         status=credit.status,
                         total_tax=credit.total_tax,
                         mobile=credit.mobile,
                         customer_name=credit.customer_name
                         )
    for item in credit.items():
        item = SoldItem.objects.create(sales=sale,
                        sku=item.sku,
                        quantity=item.quantity,
                        product_name=item.product_name,
                        total_cost=item.total_cost,
                        unit_cost=item.unit_cost,
                        product_category=item.product_category
                        )
        print item

saleor/dashboard/search/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.shortcuts import render

from ...order.models import Order
from ...product.models import Product
from ...search.views import paginate_results
from ...userprofile.models import User
from .forms import DashboardSearchForm


@staff_member_required
def search(request):
    form = DashboardSearchForm(data=request.GET or None)
    query = ''
    queryset_map = {
        Product: Product.objects.prefetch_related('images'),
        Order: Order.objects.prefetch_related('user'),
        User: User.objects.all()}
    if form.is_valid():
        results = form.search(queryset_map=queryset_map)
        page = paginate_results(results, request.GET, settings.PAGINATE_BY)
        query = form.cleaned_data['q']
    else:
        page = []
    ctx = {
        'form': form,
        'query': query,
        'results': page,
        'query_string': '?q=%s' % query}
    return render(request, 'dashboard/search/results.html', ctx)

saleor/search/views.py
from __future__ import unicode_literals

from django.core.paginator import Paginator, InvalidPage
from django.conf import settings
from django.http import Http404
from django.shortcuts import render
from .forms import SearchForm
from ..product.utils import products_with_details, products_with_availability


def paginate_results(results, get_data, paginate_by=25):
    paginator = Paginator(results, paginate_by)
    page_number = get_data.get('page', 1)
    try:
        page = paginator.page(page_number)
    except InvalidPage:
        raise Http404('No such page!')
    return page


def search(request):
    form = SearchForm(data=request.GET or None)
    if form.is_valid():
        visible_products = products_with_details(request.user)
        results = form.search(model_or_queryset=visible_products)
        results = products_with_availability(
            results, discounts=request.discounts,
            local_currency=request.currency)
        results = list(results)
        query = form.cleaned_data.get('q', '')
    else:
        results = []
        query = ''
    page = paginate_results(results, request.GET, settings.PAGINATE_BY)
    ctx = {
        'query': query,
        'results': page,
        'query_string': '?q=%s' % query}
    return render(request, 'search/results.html', ctx)

templates/dashboard/reports/creditbak/credit.html
{% extends "dashboard/base.html" %}
{% load staticfiles i18n %}
{% load i18n %}
{% load prices_i18n %}
{% load humanize %}

{% block title %}
  Credit Report
{% endblock %}
{% block breadcrumbs %}
     <li class="active"><a href="{% url 'dashboard:credit_reports' %}">Credit</a></li>
 {% endblock %}

{% block menu_creditreport_class %}active{% endblock %}
 {% block custom_css %}
   <style type="text/css">
    label.error{
      color: #FF5722;
    }
  </style>
 {% endblock %}

{% block content %}
<div class="row animated fadeIn">
    <div class="col-md-12">
      <div class="panel panel-flat">
      <div class="panel-heading">
        <h6 class="panel-title">Credit Reports</h6>
        <div class="heading-elements">
          <ul class="icons-list">
            <li><a data-action="collapse"></a></li>
            <li><a data-action="reload"></a></li>
            <li><a data-action="close"></a></li>
          </ul>
        </div>
      <a class="heading-elements-toggle"><i class="icon-more"></i></a></div>
        <div class="panel-body">
            <div class="col-md-6">
             <label>Search Credit Sale</label>
              <div class="form-group form-group-material has-feedback">
                <input class="form-control search_user" placeholder="Search details" type="text">
                <div class="form-control-feedback">
                  <i class="icon-search4 text-size-base"></i>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <label>display list size</label>
              <div class="form-group">
                 <select class="bootstrap-select list-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="0" selected>No:</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                  </select>
              </div>
            </div>
            <div class="col-md-2">
              <label>pick a date</label>
              <div class="form-group">
                <div class="input-group">
                  <input class="form-control daterange-single" type="text">
                  <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                </div>
              </div>
            </div>
            <div class="col-md-2">
             <label>Export</label>
              <div class="form-group">
                 <select class="bootstrap-select export-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="none" data-icon="fa fa-dot-circle-o">Option</option>
                    <option value="pdf" data-icon="fa-file-pdf-o">export pdf</option>
                    <option value="excel" data-icon="fa-file-excel-o">export excel</option>
                  </select>
              </div>
            </div>
      </div>
   </div>
   </div>

<div class="col-md-12">
   <div id="pagination-div">
    <div class="panel panel-flat">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <div class="table-responsives">     
                <table class="table  datatable-header-footer">
                  <caption style="margin-bottom: 10px;">
                   </caption> 
                      <thead style="border-top:1px solid #ddd;">
                        <tr>
                          <th>Transaction Date</th>
                          <th>Receipt No</th>
                          <th>Customer Name</th>
                          <th>Item Name</th>
                          <th>Unit Cost</th>
                          <th>Quantity</th>
                          <th>Total Sales (KShs)</th>
                        </tr>
                      </thead>
                      <tbody id="tb">
                        {% if items %}
                        {% for item in items %}
                          <tr>
                            <td>{{item.credit.created|date:"d-m-Y H:i a"}}</td>
                            <td>{{item.credit.invoice_number }}</td>
                            <td>{% if item.credit.user.email %}{{item.credit.user.email}}{% else %}{{item.credit.user.name}}{% endif %}</td>
                            <td>{{item.product_name}}</td>
                            <td>{{item.unit_cost}}</td>
                            <td>{{item.quantity}}</td>
                              <td><span class="pull-right">{{item.total_cost|intcomma }}</span></td>
                          </tr>
                        {% endfor %}
                        {% else %}
                         <tr><td colspan="7"><h2 class="text-center">No Sales Reports Available</h2></td></tr>
                        {% endif %}
                        </tbody>

                 </table>
              </div>
              {% if items %}
              <div class="my-paginate">
                <div class="text-center bootpag-callback" style="padding:20px;">
                  <ul class="pagination bootpag pagination-flat pagination-sm"></ul>
                  <div class="pull-right pages-nav">Page 1</div>
                </div>
                <input type="hidden" id="page_size" val="">
              </div>
              {% endif %}
             </div>
            </div>
          {% if items %}
            <div class="row">
              <div class="col-md-10 col-md-offset-1">
                 <p class="text-center" style="margin: 20px 0px;">
                   Todays Sales: Kshs 
                    {% if tsum.total_net__sum %}
                       {{tsum.total_net__sum}} 
                    {% else %}
                       0.00<br />
                    {% endif %}<br />
                   Total Sales: Kshs {{total_sales.total_net__sum}}<br />
                   Total Tax: Kshs {{ total_tax.total_tax__sum}}
                 </p>
                  <p class="text-center"> Thank you for partnering with us.<br />
                  <span>Report pullled by {{request.user.name}}</span></p>
                  <input type="hidden" class="setValue">
                  <input type="hidden" class="setName">
                  <!--<button class="btn btn-primary ck">Click</button> -->
                  
              </div>
             </div>
          {% endif %}
            </div>
<!--       <div class="panel-footer">
      <button class="btn btn-primary disabled">checki this</button>
      </div> -->
    </div>
   </div><!--pagination div-->
  </div>
</div>


{% endblock%}
{% block custom_js %}
  <script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script> 
  <script type="text/javascript" src="{% static 'backend/js/pages/form_multiselect.js' %}"></script>
<script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_select.min.js' %}"></script>
<script type="text/javascript" src="{% static 'backend/js/plugins/pagination/jquery.bootpag.js' %}"></script>
<script type="text/javascript">
 var creditPaginateUrl = "{% url 'dashboard:credit_paginate' %}";
    var creditSearchUrl = "{% url 'dashboard:credit_search' %}";
$(document).ready(function(){

    var pagination_totalsize;
    var status;
    var reportUrl = "{% url 'dashboard:credit_reports' %}";
   
    //**@ get
    $.ajax({ url: reportUrl,type: 'GET',data: {initial:'initial'},
        async:false,success: function(data){
         pagination_totalsize = data;
    }}); 

     $('.bootpag-callback').bootpag({
        total: parseInt(pagination_totalsize),
        maxVisible: 3,
        leaps: false
        }).on("page", function(event, num){
            $(".pages-nav").html("Page " + num +" of "+pagination_totalsize);
            $.get(creditPaginateUrl,{page:parseInt(num)},function(data){
               $('#tb').html(data);
            });
    }).children('.pagination').addClass('pagination-flat pagination-sm'); 

    $('.daterange-single').daterangepicker({ 
        singleDatePicker: true,
        locale:{format: 'YYYY-MM-DD'},
        showDropdowns:true
    }).on('change',function(){
      var date = $(this).val();
        $.ajax({ url: creditPaginateUrl,type: 'GET',data: {page:1, date:date }, async:false,success: function(data){
              $('#pagination-div').html(data);
        }});
    });

   $('.export-sz').selectpicker({
          iconBase: 'fa',
          tickIcon: 'fa-dot-circle-o',
          pdfIcon:'fa-file-pdf-o',
          excelIcon:'fa-file-excel-o'
    }).on('change', function(){

        var ts = $(this).val();
        if(ts == 'pdf'){
          var url = "{% url 'dashboard:reports_sales_list_pdf' %}";
          window.open(url, '_blank');

        }else if(ts=='excel'){
          window.location="{% url 'dashboard:reports_sales_list_export_csv' %}";

        }else{
          $(this).val('')
        }
    });

    $('.ck').click(function(){
      var name = $('.setName').val();
      var vl = $('.setValue').val();
        if( !name || !vl || vl == 'none'){
           alert('nothing');
        }else{
         alert(name +' and '+ vl);
        }
    });
    //**@ display size select
    $('.list-sz').selectpicker().on('change', function(){
        var ts = $(this).val();
        $.ajax({ url: creditPaginateUrl,type: 'GET',data: {page:1, size:ts}, async:false,success: function(data){
              $('#pagination-div').html(data);
        }});
     });



      var delay = (function(){
    var timer = 0;
    return function(callback, ms){
        clearTimeout (timer);
        timer = setTimeout(callback, ms);
      };
    })();

    $('.search_user').keyup(function() {
      var search_text = $(this).val();
      delay(function(){ 
         var url = creditSearchUrl;
         $.ajax({ url:url, type: 'GET',data: {page:1, q:search_text},success: function(data){
                $('#pagination-div').html(data);
         }});
      }, 500 );

    });


});

</script>
{% endblock %}

templates/dashboard/reports/creditbak/details.html
{% extends "dashboard/base.html" %}
{% load staticfiles i18n %}
{% load i18n %}
{% load prices_i18n %}
{% load prices_i18n %}
{% load humanize %}
{% block title %}
 Credit Sales Report
{% endblock %}
{% block breadcrumbs %}
     <li class="active"><a href="{% url 'dashboard:credit_list' %}">Credit Sales</a></li>
     <li>Invoice</li>
 {% endblock %}

{% block menu_report_class %}active{% endblock %}
 {% block custom_css %}
   <style type="text/css">
    label.error{
      color: #FF5722;
    }
    .table{border:1px solid #ccc}
  </style>
 {% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12" style="margin-bottom:10px;">
        <a class="btn btn-primary pull-left" href="{% url 'dashboard:sales_list' %}"><i class="icon-arrow-left13 position-left"></i> Back To Credit Sales List</a>
        <a class="btn btn-primary pull-right printPdf" data-url="{% url 'dashboard:pdf-sale-detail' pk=sale.pk%}" href="javascript:;"><i class="fa fa-file-pdf-o position-left"></i> Print</a>
        </div>
    </div>
</div>
<div class="col-md-12">
   <div id="pagination-div">
    <div class="panel panel-flat">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
               <div>
                      <div class="col-md-6 col-md-offset-3 text-center" style="color:#333;">

                        <img src="{{sale.user.image.url}}" class="center-block circle teal img-responsive img-circle" style="width: 60px;height: 60px;"/>
                        <h6 class="">Cashier: {{sale.user.name}}</h6>
                          <h5 class="">Invoice Number: {{sale.invoice_number}}</h5>
                      </div>
                    </div>
            <div class="table-responsives">
                <table class="table  datatable-header-footer">

                      <thead style="border-top:1px solid #ddd;">
                        <tr class="bg-primary">
                          <th>Transaction Date</th>
                          <th>Item Name</th>
                          <th>Unit Cost</th>
                          <th>Quantity</th>
                          <th>Total Sales (KShs)</th>
                        </tr>
                      </thead>
                      <tbody id="tb">
                        {% if items %}
                        {% for item in items %}
                          <tr>
                            <td>{{item.credit.created|date:"d-m-Y H:i a"}}</td>
                            <td>{{item.product_name}}</td>
                            <td>{{item.unit_cost}}</td>
                            <td>{{item.quantity}}</td>
                              <td><span class="pull-right">{{item.total_cost|intcomma}}</span></td>
                          </tr>
                        {% endfor %}
                         {% else %}
                         <tr><td colspan="5"><h2 class="text-center">No Items Available</h2></td></tr>
                        {% endif %}
                        </tbody>

                 </table>
              </div>
             </div>
            </div>
          {% if items %}
            <div class="row">
              <div class="col-md-6 col-md-offset-3 text-center" style="margin-top: 20px;">
                  <span>
                   Total Sales: Kshs {{sale.total_net}}<br />
                   Total Tax: Kshs {{sale.total_tax}}
                 </span><br>
                  <span> Thank you for partnering with us.<br />
                  <span>Report pullled by {{request.user.name}}</span></span>
                  <input type="hidden" class="setValue">
                  <input type="hidden" class="setName">

              </div>
             </div>
          {% endif %}
            </div>
    </div>
   </div><!--pagination div-->
  </div>
</div>


{% endblock%}
{% block custom_js %}
<script>
    $('.printPdf').on('click', function(){
       var url = $(this).data('url');
        $.get(url, function(data){
             window.open("data:application/pdf," + escape(data));
        });
    });
</script>
{% endblock %}